// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ2Nw00HucdfzejooophgzkD-fQ85_N7w',
    appId: '1:498901186900:web:933ee4fb9880dc655470c1',
    messagingSenderId: '498901186900',
    projectId: 'buymemo-f6181',
    authDomain: 'buymemo-f6181.firebaseapp.com',
    storageBucket: 'buymemo-f6181.firebasestorage.app',
    measurementId: 'G-YEN9VFP7XE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMDgBr-haRu-U-5VwaVmhmZFUFiSd6llk',
    appId: '1:498901186900:android:97b2d2ad163f8beb5470c1',
    messagingSenderId: '498901186900',
    projectId: 'buymemo-f6181',
    storageBucket: 'buymemo-f6181.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACiIKIpyBXOPVANYu6qHYSqhCGlbAIjdY',
    appId: '1:498901186900:ios:6f7eec8db84c45a35470c1',
    messagingSenderId: '498901186900',
    projectId: 'buymemo-f6181',
    storageBucket: 'buymemo-f6181.firebasestorage.app',
    iosBundleId: 'com.example.shoppingmemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACiIKIpyBXOPVANYu6qHYSqhCGlbAIjdY',
    appId: '1:498901186900:ios:6f7eec8db84c45a35470c1',
    messagingSenderId: '498901186900',
    projectId: 'buymemo-f6181',
    storageBucket: 'buymemo-f6181.firebasestorage.app',
    iosBundleId: 'com.example.shoppingmemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZ2Nw00HucdfzejooophgzkD-fQ85_N7w',
    appId: '1:498901186900:web:73b9d846f27026445470c1',
    messagingSenderId: '498901186900',
    projectId: 'buymemo-f6181',
    authDomain: 'buymemo-f6181.firebaseapp.com',
    storageBucket: 'buymemo-f6181.firebasestorage.app',
    measurementId: 'G-TJSD6SP8EF',
  );

}